Fix an issue that manifested as a problem indexing negative timestamps (ValueError: long integer out of range). Following is a description of the issue and an explanation of why the change is safe.
That's actually very interesting, because -1 produces a 64-bit long
value as expected:

  >>> from nti.zodb.containers import time_to_64bit_int
  >>> x = time_to_64bit_int( -1 )
  >>> x
  13830554455654793216L
  >>> x.bit_length()
  64
  >>> type(x)
  <type 'long'>


That should be able to go in a 64bit BTree, but as you noted, it fails:

  >>> from BTrees import family64
  >>> family64.IO.using64bits
  >>> bt = family64.IO.BTree()
  >>> bt[x] = 'str'
  Traceback (most recent call last):
    File "<console>", line 1, in <module>
  ValueError: long integer out of range

The C code is a bit hard to debug here as its all based on macros. Lets
see what the Python code does:


  >> bt = family64.IO.LOBTreePy()
  >>> bt[x] = 'str'
  Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File = "/BTrees/_base.py", line 744, in __setitem__
    self._set(self._to_key(key), self._to_value(value))
  File = "/BTrees/_base.py", line 1431, in to_long
    raise ValueError("Value out of range", v)
  ValueError: ('Value out of range', 13830554455654793216L)

Same thing, but it tells us where to look:

    try:
        # XXX Python 2.6 doesn't truncate, it spews a warning.
        if not unpack("q", pack("q", v))[0] == v: #pragma NO COVER
            if isinstance(v, int_types):
                raise ValueError("Value out of range", v)
            raise TypeError('64-bit integer expected')
    except (struct_error,
            OverflowError, #PyPy
           ):
        if isinstance(v, int_types):
            raise ValueError("Value out of range", v)
        raise TypeError('64-bit integer expected')

And there's the problem. Our time_to_64bit_int code does this:

  _long_to_double_bits = struct.Struct(b'!Q').pack
  def time_to_64bit_int( value ):
	"""
	Given a Python floating point object (usually a time value),
	return a 64-bit unsigned int that represents it. Useful for
	storing as the value in a OL tree, when you really want a float
	(since BTrees does not provide OF), or as a key in a Lx tree.
	"""

That is, we use "Q" and they use "q". We're producing unsigned values,
they're expecting signed values.

Luckily, I think we can easily switch to using 'q' because these two
properties hold:

First, all negative things would be out of range, and greater than their
positive counterparts:

   >>> : for i in range(-1, -100000, -1):
   ....:     try:
   ....:         bt[time_to_64bit_int(i)] =3D 'str'
   ....:         raise Exception('Should not get here')
   ....:     except ValueError:
   ....:         continue
   ....:

   >>> : for i in range(-1, -1000000, -1):
   ....:     assert time_to_64bit_int(i) > time_to_64bit_int(-i)
   ....:

Second, all positive values pack the same either way, so existing data
stays valid:

   >>> : for i in xrange(1, sys.maxint):
   ....:     assert struct.pack('q', i) == struct.pack('Q', i)
   ....:




git-svn-id: https://repos.nextthought.com/svn/nti-svn/NextThoughtPlatform/trunk@41893 3dfb626b-079f-4ab1-a9f6-4654e5377508